lab_staffs/urls.py
from django.urls import path
from . import views

app_name = 'lab_staffs'

urlpatterns = [
    path('', views.home, name='labstaff-home'),
    path('viewdiagnosis/', views.viewDiagnosis, name='viewDiagnosis'),
    path('viewdiagnosis/approveordeny/', views.approve_or_deny, name='approve_deny'),
    path('createreport/', views.createReport, name='createReport'),
    path('deleteandupdatereport/', views.deleteAndUpdateReport, name='deleteAndUpdateReport'),
    path('viewreport/', views.viewReport, name='viewReport'),
    path('updatereport/<int:id>', views.updateReport, name='updateReport'),
    path('', views.home, name='home'),
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name = 'users'

urlpatterns = [
    path('', views.home, name='users-home'),
    path('about/', views.about, name='users-about'),  # delete this route
    path('login/<str:usertype>', views.login_user, name='login-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('otp/',views.otp, name='otp')
]

lab_staffs/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class LabStaffProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    testType = models.CharField(max_length=30,null=True)
    testResult = models.TextField(null=True)
    staffId = models.ForeignKey('hospital_staffs.HospitalStaffProfile',on_delete=models.CASCADE,null=True)
    patientId = models.ForeignKey('patients.PatientProfile',on_delete=models.CASCADE,null=True)
    def __str__(self):
        return f'{self.user.user_type}: {self.user.username}'

lab_staffs/forms.py
from django.forms import ModelForm, forms
from hospital.models import LabTest

class labTestForm(ModelForm):
    class Meta:
        model = LabTest
        fields = ('doctor', 'patient', 'diagnosis', 'lab_test_report')


    def clean_diagnosis(self):
        diagnosis = self.cleaned_data['diagnosis']
        patients = self.cleaned_data['patient']
        exist = LabTest.objects.filter(diagnosis = diagnosis).exists()

        if exist:
            raise forms.ValidationError('lab test already exist')
        elif diagnosis.patient.user_id != patients.user_id:
            raise forms.ValidationError('Please select the matched diagnosis')
        return diagnosis

class labTestUpdateForm(ModelForm):
    class Meta:
        model = LabTest
        fields = ('doctor', 'patient', 'diagnosis', 'lab_test_report')

lab_staffs/views.py
from django.http import HttpResponse
from users.models import User

import logging
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from users.decorators import lab_staff_required
from hospital.models import Diagnosis, LabTest
from patients.models import PatientProfile
from .forms import labTestForm, labTestUpdateForm

logger = logging.getLogger(__name__)

@login_required
@lab_staff_required
# Create your views here.
def home(request):
    logger.info(f"Inside home of {request.user}")
    user = request.user.labstaffprofile
    logger.info(f"User object: {user}")

    diagnosis = Diagnosis.objects.all()

    context = {"diagnosis":diagnosis}

    return render(request, "lab_staffs/labstaff-home.html", context)

@login_required
@lab_staff_required
def viewDiagnosis(request):
    logger.info('lab staff viewing diagnosis')
    diagnosis = Diagnosis.objects.filter(lab_test_status=True)
    context = {'diagnosis': diagnosis}
    return render(request, "lab_staffs/viewDiagnosis.html", context)

@login_required
@lab_staff_required
def approve_or_deny(request):
    if request.POST:
        if 'Approve' in request.POST:
            logger.info('lab staff approve lab test')
            messages.success(request, 'Lab test report approve!')
            return redirect('lab_staffs:createReport')
        elif 'Deny' in request.POST:
            logger.info('lab staff deny labtest')
            appid = request.POST.get('app_id')
            username = request.POST.get('dia')
            user = User.objects.get(username=username)
            patientProfile = PatientProfile.objects.get(user=user)
            userDia = Diagnosis.objects.get(patient=patientProfile, appointment_id=appid)
            userDia.lab_test_status = False
            userDia.save()
            messages.success(request, 'Lab test report deny!')
    return redirect('lab_staffs:viewDiagnosis')

@login_required
@lab_staff_required
def viewReport(request):
    logger.info('lab staff viewing report')
    report = LabTest.objects.all()
    context = {'report': report}
    return render(request, "lab_staffs/viewReport.html", context)

@login_required
@lab_staff_required
def createReport(request):
    if request.POST:
        createReportForm = labTestForm(request.POST)
        if createReportForm.is_valid():
            createReportForm.save()
            logger.info('lab staff create report')
            return redirect('lab_staffs:labstaff-home')
    else:
        createReportForm = labTestForm()
    context = {'createReportForm': createReportForm}
    return render(request, "lab_staffs/createReport.html", context)

@login_required
@lab_staff_required
def deleteAndUpdateReport(request):
    if request.POST:
        if 'Delete' in request.POST:
            dia_id = request.POST.get('dia_id')
            lab_test_deleted = LabTest.objects.get(diagnosis_id = dia_id)
            lab_test_deleted.delete()
            logger.info('lab staff delete report')
            return redirect('lab_staffs:viewReport')
        elif 'Update' in request.POST:
            dia_id = request.POST.get('dia_id')
            lab_test_update = LabTest.objects.get(diagnosis_id= dia_id)
            lab_test_update_form = labTestUpdateForm(instance=lab_test_update)
            context = {'updateReportForm':lab_test_update_form,
                       'dia_id':dia_id}
            return render(request, 'lab_staffs/updateReport.html', context)
    return redirect('lab_staffs:viewReport')

@login_required
@lab_staff_required
def updateReport(request, id):
    lab_test_update = LabTest.objects.get(diagnosis_id=id)
    if request.POST:
        print(lab_test_update)
        update_form = labTestUpdateForm(request.POST, instance=lab_test_update)
        if update_form.is_valid():
            update_form.save()
            logger.info('lab staff update report')
            return redirect('lab_staffs:viewReport')
        return HttpResponse('form unvalid')
    return redirect('lab_staffs:viewReport')

lab_staffs/templates/lab_staffs/approve_or_deny.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
{% endif %}
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/createReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<div class="container">
    <h1>New Lab Test Report</h1>
    <form method="POST" novalidate>
        {% csrf_token %}
        {% for i in createReportForm %}
            <div class="create Reprot form">
                <label class="form label">{{ i.label }}</label>
                <div class="detail label" style="position: relative;">{{ i }}</div>
            </div>
        {% endfor %}
        {{ createReportForm.errors }}
        <div class="col-md-2 col-md-offset-10">
        <input type="submit" value="submit" class="btn-primary">
        </div>
    </form>
</div>
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/deleteAndUpdateReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}

{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/labstaff-home.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h1>Lab Staff Home</h1>
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/main.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body-content %}

<div class="container">
    <h1>Welcome to Dr. Yau's Clinic</h1>

    <div class="row my-5">

        <div class="col-md-3">
            <div class="content-section">
                <h3>Menu</h3>

                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:viewDiagnosis' %}">View diagonosis</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:createReport' %}">Create Report</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:viewReport' %}">View Test Report</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-9">
            {% block labstaffcontent %}{% endblock labstaffcontent %}
        </div>

    </div>
</div>

    <script type="text/javascript" src="{% static 'doctors/script.js' %}"></script>
</body>

</html>


{% endblock body-content %}

lab_staffs/templates/lab_staffs/updateReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h1>Update Lab Test Report</h1>
{% if updateReportForm %}
    <form method="POST" action="{% url 'lab_staffs:updateReport' dia_id%}">
        {% csrf_token %}
        {% for i in updateReportForm %}
            <div class="create Reprot form">
                <label class="form label">{{ i.label }}</label>
                <div class="detail label" style="position: relative;">{{ i }}</div>
            </div>
        {% endfor %}
        <input name="submit" type="submit" value="Submit">
    </form>
{% endif %}
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/viewDiagnosis.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h3>View Diagnosis</h3>
{% if diagnosis %}
    <table class="table">
        <thead>
        <th scope="col">Patient</th>
        <th scope="col">Doctor</th>
        <th scope="col">lab_tests_recommended</th>
        </thead>
        <tbody>
        {% for dia in diagnosis %}
            <tr>
            <form id="approve-options" method="POST" action="approveordeny/">
                {% csrf_token %}
                <td>{{ dia.patient.user.first_name }} {{ dia.patient.user.last_name }}</td>
                <td>{{ dia.doctor.user.first_name }} {{ dia.doctor.user.last_name }} </td>
                <td>{{ dia.lab_tests_recommended }}
                <input name="dia" type="hidden" onclick="" value="{{ dia.patient.user }}">
                <input name="app_id" type="hidden" value="{{ dia.appointment_id }}">
                <input name="Approve" type="submit" value="Approve">
                <input name="Deny" type="submit" onclick="" value="Deny">
                </td>
            </form>
            </tr>

        {% endfor %}
        </tbody>
    </table>
{% else %}
    <h4>No Diagnosis found</h4>
{% endif %}

{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/viewReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h3>View Report</h3>
{% if report %}
    <table class="table">
        <thead>
        <th scope="col">Patient</th>
        <th scope="col">Doctor</th>
        <th scope="col">Lab test report</th>
        </thead>
        <tbody>
        {% for report in report %}
            <tr>
            <form id="Delete-update-options" method="POST" action="{% url 'lab_staffs:deleteAndUpdateReport' %}">
                {% csrf_token %}
                <td>{{ report.diagnosis.patient.user.first_name }} {{ report.diagnosis.patient.user.last_name }}</td>
                <td>{{ report.diagnosis.doctor.user.first_name }} {{ report.diagnosis.doctor.user.last_name }} </td>
                <td>{{ report.lab_test_report }}
                <input name="dia_id" type="hidden" value="{{ report.diagnosis_id }}">
                <input name="Delete" type="submit" value="Delete">
                <input name="Update" type="submit" value="Update">
                </td>
            </form>
            </tr>

        {% endfor %}
        </tbody>
    </table>


{% else %}
    <h4>No Report found</h4>
{% endif %}

{% endblock labstaffcontent %}