hospital_staffs/urls.py
from django.urls import path
from . import views

app_name = 'hospital_staffs'

urlpatterns = [
    path('', views.home, name='home'),
    path('createPatient/', views.createPatient, name='createPatient'),
    path('viewPatient/', views.viewPatient, name='viewPatient'),
    path('viewRecords/', views.viewRecords, name='viewRecords'),
    path('viewLabRecords/', views.viewLabTests, name='viewLabRecords'),
    path('createTransaction/', views.createTransaction, name='createTransaction'),
    path('approveTransaction/', views.approveTransaction, name='approveTransaction'),
    path('approveAppointment/', views.approveAppointment, name='approveAppointment'),
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name = 'users'

urlpatterns = [
    path('', views.home, name='users-home'),
    path('about/', views.about, name='users-about'),  # delete this route
    path('login/<str:usertype>', views.login_user, name='login-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('otp/',views.otp, name='otp')
]

hospital_staffs/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class HospitalStaffProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=30,null=True)
    address = models.CharField(max_length=70,null=True)
    role  = models.CharField(max_length=20,null=True)

    def __str__(self):
        return f'{self.user.user_type}: {self.user.username}'

hospital_staffs/forms.py
from django.forms import ModelForm
from django.apps import apps

class CreatePatientForm(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'Diagnosis')
		fields = ('appointment',)

class ViewPatientForm(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'Diagnosis')
		fields = ('patient',)
        
class ViewPatientRecords(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'Diagnosis')
		fields = ('patient',)
        
class CreateTransaction(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'Transaction')
		fields = ('patient','diagnosis', 'amount')


class ViewLabRecords(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'LabTest')
		fields = ('patient',)

hospital_staffs/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import CreatePatientForm, ViewPatientForm, ViewPatientRecords, CreateTransaction, ViewLabRecords
from django.contrib import messages
from django.apps import apps
from django.db import IntegrityError



# Create your views here.
def home(request):
    return render(request, 'hospital_staffs/home.html')


def createPatient(request):
    form = CreatePatientForm()
    model1 = apps.get_model('hospital', 'Appointment')
    model2 = apps.get_model('hospital', 'Diagnosis')
    print(form.fields)
    if request.method == 'POST':
        try:
            flag = request.POST['appointment']
            y = model1.objects.get(id=flag)
            x = model2.objects.create(appointment = y, doctor = y.doctor, patient = y.patient)
            x.save()
            messages.success(request, 'New Record Created')
        except KeyError:
            print('KeyError')
        except Exception as e:
            print('some issue')
    context = {'form': form}
    return render(request, 'hospital_staffs/createPatient.html', context)


def viewPatient(request):
    form = ViewPatientForm()
    context = {'form': form, 'prescription': [],
               'diagnosis': [], 'checklistP':False, 'checklistD':False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewPatientForm(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'Diagnosis')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['prescription'] = []
                context['diagnosis'] = []
                for i in x.iterator():
                    if(i.prescription):
                        context['prescription'].append(i.prescription)
                    if(i.details):
                        context['diagnosis'].append(i.details)
                if(context['prescription']):
                    context['checklistP'] = True
                if(context['diagnosis']):
                    context['checklistD'] = True
                
                    
            except Exception as e:
                context['prescription'] = ["No information available as of now"]
                context['diagnosis'] = ["No information available as of now"]
            finally:
                render(request, 'hospital_staffs/viewPatient.html', context)

    return render(request, 'hospital_staffs/viewPatient.html', context)


def viewRecords(request):
    form = ViewPatientRecords()
    defText = 'Enter Patient Details fo records'
    context = {'form': form, 'records': [], 'checklist':False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewPatientRecords(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'Diagnosis')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['records'] = []
                for i in x.iterator():
                    l = ['', '', '', '']
                    l[0], l[1], l[2], l[3] = i.prescription, i.details, i.doctor, i.lab_tests_recommended
                    context['records'].append(l)
                    context['checklist'] = True
            except Exception as e:
                context['records'] = ["No information available as of now"]
            finally:
                render(request, 'hospital_staffs/viewPatientRecords.html', context)
    return render(request, 'hospital_staffs/viewPatientRecords.html', context)


def viewLabTests(request):
    form = ViewLabRecords()
    context = {'form': form, 'records': [],'checklist': False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewLabRecords(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'LabTest')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['records'] = []
                for i in x.iterator():
                    l = ['', '', '']
                    l[0], l[1], l[2] = i.doctor, i.lab_test_report, i.created
                    context['records'].append(l)
                    context['checklist'] = True
            except Exception as e:
                context['records'] = ["No information available as of now"]
            finally:
                render(request, 'hospital_staffs/viewLabRecords.html', context)
    return render(request, 'hospital_staffs/viewLabRecords.html', context)


def createTransaction(request):
    model = apps.get_model('hospital_staffs', 'HospitalStaffProfile')
    x = model.objects.filter(user=request.user.id)
    val = 0
    for i in x.iterator():
        val = i.id
        break
    form = CreateTransaction()
    if request.method == 'POST':
        form = CreateTransaction(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New Record Created')
    context = {'form': form}
    return render(request, 'hospital_staffs/createTransaction.html', context)


def approveTransaction(request):
    model = apps.get_model('hospital', 'Transaction')
    context = {'transactions': []}
    if request.method == 'POST':
        try:
            flag = request.POST['id']
            y = model.objects.get(id=flag)
            y.completed = True
            y.save()
            print(flag)
        except KeyError:
            print('KeyError')
    try:
        x = model.objects.filter(approved='t', completed=None)
        for i in x.iterator():
            context['transactions'].append(i)
    except:
        context['transactions'] = [['Record not found'] * 3]
    return render(request, 'hospital_staffs/approveTransaction.html', context)


def approveAppointment(request):
    model = apps.get_model('hospital', 'Appointment')
    context = {'transactions': []}
    if request.method == 'POST':
        try:
            flag = request.POST['id']
            y = model.objects.get(id=flag)
            y.status = True
            y.save()
            print(flag)
        except KeyError:
            print('KeyError')
    try:
        x = model.objects.filter(status=None)
        for i in x.iterator():
            context['transactions'].append(i)
    except:
        context['transactions'] = []
    return render(request, 'hospital_staffs/approveAppointment.html', context)

hospital_staffs/templates/hospital_staffs/approveAppointment.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<h4> Records: </h4>

<table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Appointment Details </th>
                <th scope="col">Patient Id</th>
                <th scope="col">Doctor Id</th>
				<th scope="col">Scheduled Date</th>
				<th scope="col">Approve</th>
            </thead>
            <tbody>
                {% for i in transactions %}
                <tr>
				
					<form id="myform{{ forloop.counter }}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id" value={{i.id}} />
							<td>{{ forloop.counter}}</td>
							<td>{{ i.appointment_details }}</td>
							<td>{{ i.patient }}</td>
							<td>{{ i.doctor }}</td>
							<td>{{ i.scheduled_date }}</td>
							<td><a href="{% url 'hospitalstaff-approveTransaction'}" onclick="document.forms[{{ forloop.counter0 }}].submit();return false;">Approve</a></td>
					  </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/approveTransaction.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<h4> Records: </h4>

<table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Amount</th>
                <th scope="col">Patient Id</th>
                <th scope="col">Diagnosis</th>
				<th scope="col">Approve</th>
            </thead>
            <tbody>
                {% for i in transactions %}
                <tr>
				
					<form id="myform{{ forloop.counter }}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id" value={{i.id}} />
							<td>{{ forloop.counter}}</td>
							<td>{{ i.amount }}</td>
							<td>{{ i.patient }}</td>
							<td>{{ i.diagnosis}}</td>
							<td><a href="{% url 'hospitalstaff-approveTransaction'}" onclick="document.forms[{{ forloop.counter0 }}].submit();return false;">Approve</a></td>
					  </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/createPatient.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}



        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>Create New Patient Record</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/createTransaction.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}



        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>Create Transactions</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/home.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body-content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'patients/styles.css' %}">
    <title>Document</title>
</head>

<body>

    <div class="container">
        <h1>Welcome to Dr. Yau's Clinic</h1>

        <div class="row my-5">

            <div class="col-md-3">
                <div class="content-section">
                    <h3>Menu</h3>
                    <!-- <ul class="list-group patient-sidebar">
                        <li id="home" onclick="switchPage('home')">Home</li>
                        <li id="appointments" onclick="switchPage('appointments')">Appointments</li>
                        <li id="diagnosis" onclick="switchPage('diagnosis')">
                            Diagnosis</li>
                        <li id="prescriptions" onclick="switchPage('prescriptions')">Prescriptions</li>
                        <li id="reports" onclick="switchPage('reports')">
                            Reports</li>
                        <li id="insurance" onclick="switchPage('insurance')">
                            Insurance</li>
                        <li id="transactions" onclick="switchPage('transactions')">Transactions</li>
                        <li id="profile" onclick="switchPage('profile')">My Profile</li>
                    </ul> -->
                    <ul class="nav flex-column">
                        <li class="nav-item"> <a class="nav-link"  href="{% url 'hospital_staffs:createPatient' %}">Create Patient Records</a></li>
                      <li class="nav-item"><a class="nav-link"  href="{% url 'hospital_staffs:viewPatient' %}">View Patient Diagnosis and Prescription</a></li>
                      <li class="nav-item"><a  class="nav-link"  href="{% url 'hospital_staffs:viewRecords' %}">View Patient Records</a></li>
					  <li class="nav-item"><a class="nav-link"  href="{% url 'hospital_staffs:viewLabRecords' %}">View Lab Records</a></li>
                      <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:createTransaction' %}">Create Transactions</a></li>
					  <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:approveTransaction' %}">Approve Transactions</a></li>					  
                   	  <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:approveAppointment' %}">Approve Appointments</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                {% block patientcontent %}{% endblock patientcontent %}

                <!-- <div id="home-view" style="display:none;">
                    <h2>Home</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="appointments-view" style="display:none;">
                    <h2>Appointments</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="diagnosis-view" style="display:none;">
                    <h2>Diagnosis</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="prescriptions-view" style="display:none;">
                    <h2>Prescriptions</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="reports-view" style="display:none;">
                    <h2>Reports</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="insurance-view" style="display:none;">
                    <h2>Insurance</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="transactions-view" style="display:none;">
                    <h2>Transactions</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="profile-view" style="display:none;">
                    <h2>Profile</h2>
                    <div class="content-section">
                        <div class="media">
                            <img class="rounded-circle account-img" src="{{ user.patientprofile.image.url }}" alt="">
                            <div class="media-body">
                                <h2 class="account-heading">{{ user.username }}</h2>
                                <p class="text-secondary">{{ user.email }}</p>
                            </div>
                        </div>
                        FORM HERE
                        <form name="profile-form" method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ pform | crispy }}
                            <div class="row">
                                <div class="col">
                                    <img src="{{ profile.user.patientprofile.image.url }}" alt="Profile Image Not Found!"
                                        style="width: 100px; aspect-ratio: 1;">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="username" class="form-label">Username</label>
                                    <input id="username" class="form-control" name="username" type="text" value="{{ profile.user.username }}" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="email" class="form-label">Email</label>
                                    <input id="email" class="form-control" name="email" type="text" value="{{ profile.user.email }}" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="address" class="form-label">Address</label>
                                    <input id="address" name="address" type="text" class="form-control" value="{{ profile.address }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="insurance" class="form-label">Insurance</label>
                                    <input id="insurance" name="insurance" type="text" class="form-control" value="{{ profile.insurance }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col"></div>
                            </div>
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Profile Info</legend>
                                {{ u_form|crispy }}
                                {{ p_form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Update Profile</button>
                            </div>
                        </form>
                    </div>
                </div> -->



            </div>

        </div>
    </div>


    <script type="text/javascript" src="{% static 'patients/script.js' %}"></script>
</body>

</html>


{% endblock body-content %}

hospital_staffs/templates/hospital_staffs/viewLabRecords.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}



        <form action="" method="get">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>View Lab Records</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
		<br>
{% if checklist %}
        <table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Test Type </th>
                <th scope="col">Test Result</th>
                <th scope="col">Staff Id</th>
            </thead>
            <tbody>
                {% for i in records %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ i.0 }}</td>
                    <td>{{ i.1 }}</td>
                    <td>{{ i.2 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Lab Tests found</h4>
        {% endif %}





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/viewPatient.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}



        <form action="" method="get">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>View Diagnosis and Prescription</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
		<br>
		
		
		{% if checklistP %}
        <table class="table">
            <thead>
				<th scope="col">Record </th>
                <th scope="col">Prescription </th>
            </thead>
            <tbody>
                {% for i in prescription %}
                <tr>
                    <td>{{ forloop.counter}}</td>
					<td>{{ i}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Prescriptions found</h4>
        {% endif %}
		<br>
				{% if checklistD %}
        <table class="table">
            <thead>
				<th scope="col">Record </th>
                <th scope="col">Diagnosis </th>
            </thead>
            <tbody>
                {% for i in diagnosis %}
                <tr>
                    <td>{{ forloop.counter}}</td>
					<td>{{ i}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Diagnosis found</h4>
        {% endif %}







{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/viewPatientRecords.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}



        <form action="" method="get">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>View Patient Records</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
		<br>


{% if checklist %}
        <table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Prescription </th>
                <th scope="col">Diagnosis</th>
                <th scope="col">DoctorId</th>
				<th scope="col">LabTestId</th>
            </thead>
            <tbody>
                {% for i in records %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ i.0 }}</td>
                    <td>{{ i.1 }}</td>
                    <td>{{ i.2 }}</td>
					<td>{{ i.3 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Records found</h4>
        {% endif %}





{% endblock patientcontent %}