doctors/urls.py
from django.urls import path
from . import views

app_name = "doctors"

urlpatterns = [
    path('', views.home, name='home'),
    path('appointments/', views.appointments, name='appointments'),
    path('diagnosis/', views.diagnosis, name='diagnosis'),
    path('prescriptions/', views.prescriptions, name='prescriptions'),
    path('reports/', views.reports, name='reports'),
    path('profile/', views.profile, name='profile')
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name = 'users'

urlpatterns = [
    path('', views.home, name='users-home'),
    path('about/', views.about, name='users-about'),  # delete this route
    path('login/<str:usertype>', views.login_user, name='login-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('otp/',views.otp, name='otp')
]

doctors/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class DoctorProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    staffId = models.ForeignKey('hospital_staffs.HospitalStaffProfile',on_delete=models.CASCADE,null=True)
    timeSlot = models.DateTimeField(auto_now_add=True,null=True)
    patientId = models.ForeignKey('patients.PatientProfile',on_delete=models.CASCADE,null=True)

    def __str__(self):
        return f'{self.user.user_type}: {self.user.username}'

doctors/forms.py
from django import forms
from datetime import datetime
from django.forms import ModelForm
from django.apps import apps


class ProfileForm(forms.Form):
    username = forms.CharField(
        label='Username', max_length=100, required=False, disabled=True)
    email = forms.CharField(label='Email', max_length=100,
                            required=False, disabled=True)
    address = forms.CharField(label='Address', max_length=100, required=False)
    insurance = forms.CharField(
        label='Insurance', max_length=100, required=False)
        
class UpdatePatientForm(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'Diagnosis')
		fields = ('patient',)

class ViewLabRecords(ModelForm):
	class Meta:
		model = apps.get_model('hospital', 'LabTest')
		fields = ('patient',)

doctors/views.py
from django.http import HttpResponse
from django.shortcuts import render
import logging
from django.apps import apps

from django.contrib.auth.decorators import login_required

from hospital.forms import LabTestRecommendationForm
from hospital.models import Appointment, Diagnosis, LabTest
from doctors.models import DoctorProfile
from users.decorators import doctor_required
from django.shortcuts import render, get_object_or_404
from .forms import ProfileForm, UpdatePatientForm,ViewLabRecords
from django.contrib import messages

from django.contrib.auth import get_user_model

User = get_user_model()
logger = logging.getLogger(__name__)

prescriptions_list = []
reports_list = [
    {
        'Id': 1,
        'testType': 'Type1',
        'testResult': 'All Ok',
        'patientID_Id': 1,
        'staffID_Id': 3,
        'userID_Id': 1
    },
    {
        'Id': 2,
        'testType': 'Type1',
        'testResult': 'All Ok',
        'patientID_Id': 1,
        'staffID_Id': 3,
        'userID_Id': 1
    },
    {
        'Id': 3,
        'testType': 'Type1',
        'testResult': 'All Ok',
        'patientID_Id': 1,
        'staffID_Id': 3,
        'userID_Id': 1
    },
    {
        'Id': 4,
        'testType': 'Type1',
        'testResult': 'All Ok',
        'patientID_Id': 1,
        'staffID_Id': 3,
        'userID_Id': 1
    },
]

@login_required
@doctor_required
# Create your views here.
# def home(request):
#     print(f"Inside home of {request.user}")
#     user = get_object_or_404(DoctorProfile, user=request.user)
#     print(f"User object: {user}")
#
#     recommendation_form = LabTestRecommendationForm()
#
#     context = {
#         'appointments': Appointment.objects.filter(doctor=user),
#         'diagnosis': Diagnosis.objects.filter(doctor=user),
#         'lab_tests': LabTest.objects.filter(doctor=user),
#         'recommendation_form': recommendation_form
#     }
#     return render(request, 'doctors/home.html', context)
def home(request):
    print(f"Inside home of {request.user}")
    user = request.user.doctorprofile
    print(f"User object: {user}")

    recommendation_form = LabTestRecommendationForm()

    context = {
        'appointments': Appointment.objects.filter(doctor=user),
        'diagnosis': Diagnosis.objects.filter(doctor=user),
        'lab_tests': LabTest.objects.filter(doctor=user),
        'recommendation_form': recommendation_form
    }
    return render(request, 'doctors/home.html', context)


def prescriptions(request):
    form = UpdatePatientForm()
    context = {'form': form, 'records': [], 'checklist':False}
    if request.method == 'POST' and 'patient' not in request.POST:
        model = apps.get_model('hospital', 'Diagnosis')
        try:
            flag = request.POST['id']
            y = model.objects.get(id=flag)
            if('prescription'in request.POST):
                if not request.POST['prescription']:
                    y.prescription = None
                    print(y.prescription)
                    print('a')
                y.prescription = request.POST['prescription']
                print(request.POST['prescription'])
            if('details' in request.POST):
                if not request.POST['details']:
                    y.details = None
                y.details = request.POST['details']  
            if('lab' in request.POST):
                if not request.POST['lab']:
                    y.lab_tests_recommended = None
                y.lab_tests_recommended = request.POST['lab']               
            y.save()
        except KeyError:
            print('KeyError')
        finally:
                render(request, 'doctors/prescriptions.html', context)
    if request.method == 'POST' and 'patient' in request.POST:
        user = request.user.doctorprofile
        form = UpdatePatientForm(request.POST)
        if form.is_valid():
            model = apps.get_model('hospital', 'Diagnosis')
            try:
                x = model.objects.filter(patient=request.POST['patient'], doctor = user)
                context['records'] = []
                for i in x.iterator():
                    context['records'].append(i)
                    context['checklist'] = True
            except Exception as e:
                print('Some issue')
            finally:
                render(request, 'doctors/prescriptions.html', context)
    return render(request, 'doctors/prescriptions.html', context)


def diagnosis(request):
    print(f"{request.user}: Diagnosis page")

    diagnosis_list = Diagnosis.objects.filter(doctor=request.user.doctorprofile)
    print(f"{request.user}: Previous diagnosis: {diagnosis_list}")

    context = {
        'diagnosis_list': diagnosis_list,
    }
    return render(request, 'doctors/diagnosis.html', context=context)


def appointments(request):
    user = request.user.doctorprofile
    context = {
        'appointments': Appointment.objects.filter(doctor=user),
    }

    return render(request, 'doctors/appointments.html', context=context)


def reports(request):
    form = ViewLabRecords()
    context = {'form': form, 'records': [],'checklist': False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewLabRecords(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'LabTest')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['records'] = []
                for i in x.iterator():
                    l = ['', '', '']
                    l[0], l[1], l[2] = i.doctor, i.lab_test_report, i.created
                    context['records'].append(l)
                    context['checklist'] = True
            except Exception as e:
                context['records'] = ["No information available as of now"]
            finally:
                render(request, 'doctors/reports.html', context)
    return render(request, 'doctors/reports.html', context=context)

def profile(request):
    form = ProfileForm()
    # profile = PatientProfile.objects.all()[0]
    #form = ProfileForm(initial={'username': profile.user.username, 'email': profile.user.email,
    #                             'address': profile.address, 'insurance': profile.insurance})

    # if(request.method == 'POST'):
    #     form = ProfileForm(request.POST)
    #     if(form.is_valid()):
    #         data = form.cleaned_data
    #         profile.address = data['address']
    #         profile.insurance = data['insurance']
    #         profile.save()
    #         messages.success(request, 'Profile Updated')
    #         return redirect(reverse('patients:patient-home'))
    #     else:
    #         form = ProfileForm(initial={'username': profile.user.username, 'email': profile.user.email,
    #                                     'address': profile.address, 'insurance': profile.insurance})

    context = {
        'form': form,
        'profile': profile
    }
    return render(request, 'doctors/profile.html', context=context)
    

doctors/templates/doctors/appointments.html
{% extends 'doctors/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block doctorcontent %}


<div class="row my-3">
    <div class="col">
        {% if appointments %}
        <table class="table">
            <thead>
                <!-- <th scope="col">S.No.</th> -->
                <th scope="col">Status</th>
                <th scope="col">Description</th>
                <th scope="col">Patient</th>
                <th scope="col">Scheduled Date</th>
            </thead>
            <tbody>
                {% for app in appointments %}
                <tr>
                    <td>{{ app.status }}</td>
                    <td>{{ app.appointment_details }}</td>
                    <td>{{ app.patient.user.username }}</td>
                    <td>{{ app.scheduled_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Appointments found!</h4>
        {% endif %}

    </div>
</div>

{% endblock doctorcontent %}

doctors/templates/doctors/diagnosis.html
{% extends 'doctors/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block doctorcontent %}

<div class="row mb-3">
    <div class="col">
        <h2>Diagnosis Summary</h2>
    </div>
</div>

<div class="row my-3">
    <div class="col">
        {% if diagnosis_list %}
        <table class="table">
            <thead>
                <th scope="col">Patient</th>
                <th scope="col">Comments</th>
                <th scope="col">Prescription</th>
                <th scope="col">Date</th>
            </thead>
            <tbody>
                {% for d in diagnosis_list %}
                <tr>
                    <td>${{ "50" }}</td>
                    <td>{{ d.patient.user.first_name }} {{ d.patient.user.last_name }}</td>
                    <td>{{ d.details }}</td>
                    <td>{{ d.prescription }}</td>
                    <td>{{ d.created }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Diagnosis found</h4>
        {% endif %}

    </div>
</div>

{% endblock doctorcontent %}

doctors/templates/doctors/home.html
{% extends 'doctors/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block doctorcontent %}


<div class="container">

    <h2>Home</h2>
    {% for appointment in appointments %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ appointment.patient }}</a>
                <small class="text-muted">{{ appointment.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
            <p class="article-content">{{ appointment.description }}</p>
        </div>
    </article>
    {% endfor %}

</div>


{% endblock doctorcontent %}

doctors/templates/doctors/main.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body-content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'patients/styles.css' %}">
    <title>Document</title>
</head>

<body>

    <div class="container">
        <h1>Welcome to Dr. Yau's Clinic</h1>

        <div class="row my-5">

            <div class="col-md-3">
                <div class="content-section">
                    <h3>Menu</h3>

                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'doctors:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'doctors:appointments' %}">Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'doctors:prescriptions' %}">View and Update Patient Records</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'doctors:reports' %}">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                {% block doctorcontent %}{% endblock doctorcontent %}
            </div>

        </div>
    </div>


    <script type="text/javascript" src="{% static 'doctors/script.js' %}"></script>
</body>

</html>


{% endblock body-content %}

doctors/templates/doctors/prescriptions.html
{% extends 'doctors/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block doctorcontent %}

        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>View Patient Records</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
		<br>


{% if checklist %}
        <table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Prescription </th>
                <th scope="col">Diagnosis</th>
                <th scope="col">Doctor</th>
				<th scope="col">LabTest Recommended</th>
				<th scope="col">Approve</th>
            </thead>
            <tbody>
                {% for i in records %}
                <tr>
				
					<form id="myform{{ forloop.counter }}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id" value={{i.id}} />
							<td>{{ forloop.counter}}</td>
							<td><input type="text" name="prescription" value={{ i.prescription }} /></td>
							<td><input type="text" name="details" value={{ i.details }} /></td>
							<td>{{ i.doctor }}</td>
							<td><input type="text" name="lab" value={{ i.lab_tests_recommended }} /></td>
							<td><a href="{% url 'doctors:prescriptions'}" onclick="document.forms[{{ forloop.counter }}].submit();return false;">Approve</a></td>
					  </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Records found</h4>
        {% endif %}

{% endblock doctorcontent %}

doctors/templates/doctors/profile.html
{% extends 'doctors/main.html' %}
{% load crispy_forms_tags %}

{% block doctorcontent %}

    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ doctor.user.doctorprofile.image.url }}" alt="">
            <!-- <div class="media-body">
                <h2 class="account-heading">{{ profile.user.username }}</h2>
                <p class="text-secondary">{{ profile.user.email }}</p>
            </div> -->
        </div>
        <!-- FORM HERE -->
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ form|crispy }}
                <!-- {{ p_form|crispy }} -->
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update Profile</button>
            </div>
        </form>
    </div>

{% endblock doctorcontent %}

doctors/templates/doctors/reports.html
{% extends 'doctors/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block doctorcontent %}

 <form action="" method="get">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>View Lab Records</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
		<br>
{% if checklist %}
        <table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Test Type </th>
                <th scope="col">Test Result</th>
                <th scope="col">Staff Id</th>
            </thead>
            <tbody>
                {% for i in records %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ i.0 }}</td>
                    <td>{{ i.1 }}</td>
                    <td>{{ i.2 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Lab Tests found</h4>
        {% endif %}

{% endblock doctorcontent %}